/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'SimiansBlogStandard\'">' + entity + '</span>' + html;
	}
	var icons = {
			'ico-arrow-up-left' : '&#xe008;',
			'ico-arrow-up' : '&#xe009;',
			'ico-arrow-up-right' : '&#xe00a;',
			'ico-arrow-right' : '&#xe00b;',
			'ico-arrow-down-right' : '&#xe00c;',
			'ico-arrow-down' : '&#xe00d;',
			'ico-arrow-down-left' : '&#xe00e;',
			'ico-arrow-left' : '&#xe00f;',
			'ico-arrow-left-2' : '&#xe010;',
			'ico-arrow-down-2' : '&#xe011;',
			'ico-arrow-up-2' : '&#xe012;',
			'ico-arrow-right-2' : '&#xe013;',
			'ico-arrow-left-3' : '&#xe014;',
			'ico-arrow-down-3' : '&#xe015;',
			'ico-arrow-up-3' : '&#xe016;',
			'ico-arrow-right-3' : '&#xe017;',
			'ico-undo' : '&#xe018;',
			'ico-redo' : '&#xe019;',
			'ico-undo-2' : '&#xe01a;',
			'ico-redo-2' : '&#xe01b;',
			'ico-forward' : '&#xe01c;',
			'ico-reply' : '&#xe01d;',
			'ico-loop' : '&#xe01e;',
			'ico-arrow-right-4' : '&#xe000;',
			'ico-arrow-left-4' : '&#xe001;',
			'ico-arrow-up-4' : '&#xe002;',
			'ico-arrow-down-4' : '&#xe003;',
			'ico-arrow-down-left-2' : '&#xe004;',
			'ico-arrow-down-right-2' : '&#xe005;',
			'ico-arrow-up-left-2' : '&#xe006;',
			'ico-arrow-up-right-2' : '&#xe007;',
			'ico-menu' : '&#xe01f;',
			'ico-play' : '&#xe020;',
			'ico-pause' : '&#xe021;',
			'ico-forward-2' : '&#xe022;',
			'ico-backward' : '&#xe023;',
			'ico-first' : '&#xe024;',
			'ico-last' : '&#xe025;',
			'ico-stop' : '&#xe026;',
			'ico-previous' : '&#xe027;',
			'ico-next' : '&#xe028;',
			'ico-eject' : '&#xe029;',
			'ico-volume-mute' : '&#xe02a;',
			'ico-volume-low' : '&#xe02b;',
			'ico-volume-mute-2' : '&#xe02c;',
			'ico-off' : '&#xf011;',
			'ico-bolt' : '&#xe02d;',
			'ico-connection' : '&#xe02e;',
			'ico-alert' : '&#xe02f;',
			'ico-move' : '&#xe03b;',
			'ico-expand' : '&#xe03c;',
			'ico-home' : '&#xe030;',
			'ico-flag' : '&#xe031;',
			'ico-fire' : '&#xe032;',
			'ico-calendar' : '&#xf073;',
			'ico-shopping-cart' : '&#xf07a;',
			'ico-pencil' : '&#xe033;',
			'ico-clock' : '&#xe034;',
			'ico-key' : '&#xe06b;',
			'ico-wrench' : '&#xf0ad;',
			'ico-cog' : '&#xf013;',
			'ico-heart' : '&#xf004;',
			'ico-star' : '&#xe035;',
			'ico-folder-close' : '&#xf07b;',
			'ico-folder-open' : '&#xf07c;',
			'ico-file' : '&#xe036;',
			'ico-copy' : '&#xe037;',
			'ico-envelope' : '&#xe111;',
			'ico-envelope-2' : '&#xe112;',
			'ico-suitcase' : '&#xf0f2;',
			'ico-user' : '&#xe038;',
			'ico-user-2' : '&#xe03d;',
			'ico-print' : '&#xe03e;',
			'ico-tag' : '&#xe0ac;',
			'ico-locked' : '&#xe0b9;',
			'ico-unlocked' : '&#xe0b8;',
			'ico-notebook' : '&#xe03f;',
			'ico-bookmark' : '&#xe040;',
			'ico-link' : '&#xe041;',
			'ico-zoom-out' : '&#xe072;',
			'ico-magnifier' : '&#xe06f;',
			'ico-zoom-in' : '&#xe070;',
			'ico-blocked' : '&#xe042;',
			'ico-plus' : '&#xe043;',
			'ico-circle-arrow-left' : '&#xf0a8;',
			'ico-circle-arrow-up' : '&#xf0aa;',
			'ico-circle-arrow-right' : '&#xf0a9;',
			'ico-circle-blank' : '&#xf10c;',
			'ico-circle' : '&#xf111;',
			'ico-circle-arrow-down' : '&#xf0ab;',
			'ico-pin' : '&#xe0e2;',
			'ico-pin-2' : '&#xe0e1;',
			'ico-question' : '&#xe045;',
			'ico-exclamation-sign' : '&#xf06a;',
			'ico-warning' : '&#xe047;',
			'ico-spam' : '&#xe046;',
			'ico-light-bulb' : '&#xe048;',
			'ico-profile' : '&#xe0e6;',
			'ico-picture' : '&#xf03e;',
			'ico-clipboard' : '&#xe15a;',
			'ico-clipboard-2' : '&#xe15b;',
			'ico-minus-sign' : '&#xf056;',
			'ico-minus' : '&#xf068;',
			'ico-plus-2' : '&#xe049;',
			'ico-feather' : '&#xe044;',
			'ico-paperplane' : '&#xe04a;',
			'ico-air' : '&#xe04b;',
			'ico-history' : '&#xe04c;',
			'ico-ying-yang' : '&#xe14d;',
			'ico-coin' : '&#xe04d;',
			'ico-medal' : '&#xe069;',
			'ico-lab' : '&#xe0fe;',
			'ico-3d-glasses' : '&#xe05c;',
			'ico-site-map' : '&#xe04f;',
			'ico-pictures' : '&#xe050;',
			'ico-cogs' : '&#xe0bb;',
			'ico-space-invaders' : '&#xe07b;',
			'ico-cube' : '&#xe0b5;',
			'ico-pil' : '&#xe08a;',
			'ico-injection' : '&#xe08b;',
			'ico-attachment' : '&#xe0dc;',
			'ico-stats' : '&#xe0fb;',
			'ico-stats-2' : '&#xe0fc;',
			'ico-download' : '&#xe0fd;',
			'ico-piano' : '&#xe11c;',
			'ico-globe' : '&#xe14b;',
			'ico-atom' : '&#xe148;',
			'ico-qrcode' : '&#xe051;',
			'ico-barcode' : '&#xe052;',
			'ico-equalizer' : '&#xe053;',
			'ico-spinner' : '&#xe054;',
			'ico-spinner-2' : '&#xe055;',
			'ico-spinner-3' : '&#xe056;',
			'ico-meter' : '&#xe058;',
			'ico-rocket' : '&#xe059;',
			'ico-happy' : '&#xe05a;',
			'ico-tongue' : '&#xe05b;',
			'ico-sad' : '&#xe05d;',
			'ico-wink' : '&#xe05e;',
			'ico-grin' : '&#xe05f;',
			'ico-cool' : '&#xe060;',
			'ico-angry' : '&#xe061;',
			'ico-evil' : '&#xe062;',
			'ico-shocked' : '&#xe063;',
			'ico-confused' : '&#xe064;',
			'ico-wondering' : '&#xe065;',
			'ico-neutral' : '&#xe066;',
			'ico-smiley' : '&#xe067;',
			'ico-users' : '&#xe039;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/ico-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};